"""Exceptions."""
# -*- coding: utf-8 -*-


class ProgressBarException(Exception):
    """Any exception generated by ProgressBarException."""
    pass


class ProgressBarIntegerNumberError(ProgressBarException):
    """Integer number to ProgressBar."""
    def __init__(self, value):
        self.value = value

    def __str__(self):
        return repr('It must be a integer: {}'.format(self.value))


class ProgressBarNumberError(ProgressBarException):
    """Invalid number to ProgressBar."""
    def __init__(self, value):
        self.value = value

    def __str__(self):
        text = 'It must be an integer greater than 0 and less than 100: {}'
        return repr(text.format(self.value))


class ProgressBarHigherNumberError(ProgressBarException):
    """Invalid number to ProgressBar."""

    def __str__(self):
        return repr("The 'start' number must be less than the 'end'")
